name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci
      - run: npm run build

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 363.0.0"

      - run: |
          if [ ! -f ./Dockerfile ]; then
            echo "Dockerfile not found in the root directory."
            exit 1
          fi

      - run: |
          gcloud auth configure-docker --quiet
          docker build -t europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/finance/finance .
          docker push europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/finance/finance

      - run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud run deploy filip-sjolander \
            --image europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/finance/finance \
            --platform managed \
            --region europe-north1 \
            --allow-unauthenticated
