name: nextjs-cloud-run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - run: npm ci
    - run: npm test
    - run: npm run build

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Deploy to Cloud Run'
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud run deploy YOUR_SERVICE_NAME \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/YOUR_IMAGE_NAME \
          --platform managed \
          --region europe-north1 \
          --allow-unauthenticated
